### ISSUE TITLE
build fails, might be conda-build issue

### ISSUE THREAD

**Issue by barentine** [python-microscopy/pyme-conda-recipes#2]
$ conda list | grep build
conda-build               3.18.11                  py36_0    anaconda

abridged, `conda build python-microscopy`
```
Adding in variants from /tmp/tmpe29hm8fx/info/recipe/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /tmp/tmpe29hm8fx/info/recipe/conda_build_config.yaml
INFO conda_build.variants:_combine_spec_dictionaries(188): Adding in variants from /tmp/tmpe29hm8fx/info/recipe/conda_build_config.yaml
Nothing to test for: /home/ubuntu/miniconda3/conda-bld/linux-64/python-microscopy-20.02.12-py36_0.tar.bz2
Renaming work directory,  /home/ubuntu/miniconda3/conda-bld/python-microscopy_1581693838244/work  to  /home/ubuntu/miniconda3/conda-bld/python-microscopy_1581693838244/work_moved_python-microscopy-20.02.12-py36_0_linux-64_main_build_loop
From https://github.com/python-microscopy/python-microscopy
 * [new ref]                    -> _conda_cache_origin_head
Cloning into '/home/ubuntu/miniconda3/conda-bld/python-microscopy_1581693838244/work'...
done.
checkout: 'HEAD'
Your branch is up-to-date with 'origin/_conda_cache_origin_head'.
==> git log -n1 <==

commit a4302f0c8d0f62e612ba5f94e1c164467ce00d2f
Author: David Baddeley <david.baddeley.nz@gmail.com>
Date:   Fri Feb 14 16:23:57 2020 +1300

    ruleserver documentation updates

==> git describe --tags --dirty <==

20.02.12-85-ga4302f0

==> git status <==

On branch _conda_cache_origin_head
Your branch is up-to-date with 'origin/_conda_cache_origin_head'.

nothing to commit, working directory clean

Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
BUILD START: ['python-microscopy-20.02.12-py27_0.tar.bz2']
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                   
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 469, in main
    execute(sys.argv[1:])
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 460, in execute
    verify=args.verify, variants=args.variants)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 2344, in build_tree
    notest=notest,
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1408, in build
    create_build_envs(top_level_pkg, notest)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1282, in create_build_envs
    channel_urls=tuple(m.config.channel_urls))
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda_build/environ.py", line 757, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/plan.py", line 474, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
    should_retry_solve)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 158, in solve_for_diff
    force_remove, should_retry_solve)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 281, in solve_final_state
    ssc = self._run_sat(ssc)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 808, in _run_sat
    should_retry_solve=ssc.should_retry_solve
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 1318, in solve
    self.find_conflicts(specs, specs_to_add, history_specs)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 347, in find_conflicts
    bad_deps = self.build_conflict_map(specs, specs_to_add, history_specs)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 507, in build_conflict_map
    root, search_node, dep_graph, num_occurances)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 369, in breadth_first_search_for_dep_graph
    last_spec = MatchSpec.union((path[-1], target_paths[-1][-1]))[0]
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/models/match_spec.py", line 481, in union
    return cls.merge(match_specs, union=True)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/models/match_spec.py", line 475, in merge
    reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/models/match_spec.py", line 475, in <lambda>
    reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/models/match_spec.py", line 502, in _merge
    final = this_component.union(that_component)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/models/match_spec.py", line 764, in union
    return '|'.join(options)
TypeError: sequence item 0: expected str instance, Channel found
(base) ubuntu@blofeld:~/code/pyme-conda-recipes$ 

```

**Comment by David-Baddeley** [comment]
I suspect it's a conda bug. Was working fine for me on windows on Friday.

**Comment by barentine** [comment]
Which version of conda-build, @David-Baddeley ?

**Comment by barentine** [comment]
I think it's actually a conda issue, since it's failing in match spec, and now I see that I can also get a different output, which is an unsatisfiable error, which is also reported here.

Probably because I was building for numpy 1.16 and pymedepends thinks that's no good.
```
$ conda list
# packages in environment at /home/ubuntu/miniconda3:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   py36_0    anaconda
appdirs                   1.4.3                    pypi_0    pypi
asn1crypto                1.3.0                    py36_0    anaconda
attrs                     19.3.0                     py_0    anaconda
babel                     2.8.0                      py_0    anaconda
beautifulsoup4            4.8.2                    py36_0    anaconda
blas                      1.0                         mkl    anaconda
bzip2                     1.0.8                h7b6447c_0    anaconda
ca-certificates           2020.1.1                      0    anaconda
cairo                     1.14.12              h8948797_3    anaconda
certifi                   2019.11.28               py36_0    anaconda
cffi                      1.14.0           py36h2e261b9_0    anaconda
chardet                   3.0.4                 py36_1003    anaconda
cheroot                   8.2.1                    py36_0    anaconda
cherrypy                  18.1.1                   py36_0    anaconda
cloudpickle               1.3.0                      py_0    anaconda
conda                     4.8.2                    py36_0    anaconda
conda-build               3.17.8                   py36_0    anaconda
conda-package-handling    1.6.0            py36h7b6447c_0    anaconda
contextlib2               0.6.0.post1                py_0    anaconda
cryptography              2.8              py36h1ba5d50_0    anaconda
cycler                    0.10.0                   py36_0    anaconda
cython                    0.29.13          py36he6710b0_0    anaconda
cytoolz                   0.10.1           py36h7b6447c_0    anaconda
dask-core                 2.10.1                     py_0    anaconda
dbus                      1.13.12              h746ee38_0    anaconda
decorator                 4.4.1                      py_0    anaconda
dispatch                  1.0                      py36_0    david_baddeley
docutils                  0.16                     py36_0    anaconda
expat                     2.2.6                he6710b0_0    anaconda
fftw                      3.3.8                h7b6447c_3    anaconda
filelock                  3.0.12                     py_0    anaconda
fontconfig                2.13.0               h9420a91_0    anaconda
freetype                  2.9.1                h8a8886c_1    anaconda
fribidi                   1.0.5                h7b6447c_0    anaconda
future                    0.18.2                   py36_0    anaconda
gettext                   0.19.8.1             h9b4dc7a_1    anaconda
glib                      2.56.2               hd408876_0    anaconda
glob2                     0.7                        py_0    anaconda
graphite2                 1.3.13               h23475e2_0    anaconda
gst-plugins-base          1.14.0               hbbd80ab_1    anaconda
gstreamer                 1.14.0               hb453b48_1    anaconda
harfbuzz                  1.8.8                hffaf4a1_0    anaconda
hdf5                      1.10.1               hb0523eb_0    anaconda
icu                       58.2                 h211956c_0    anaconda
idna                      2.8                      py36_0    anaconda
ifaddr                    0.1.6                      py_0    david_baddeley
imageio                   2.6.1                    py36_0    anaconda
imagesize                 1.2.0                      py_0    anaconda
importlib_metadata        1.5.0                    py36_0    anaconda
intel-openmp              2020.0                      166    anaconda
jaraco.functools          2.0                   py36_1000    anaconda
jinja2                    2.11.1                     py_0    anaconda
joblib                    0.14.1                     py_0    anaconda
jpeg                      9b                   habf39ab_1    anaconda
kiwisolver                1.1.0            py36he6710b0_0    anaconda
libarchive                3.3.3                h5d8350f_5    anaconda
libedit                   3.1.20181209         hc058e9b_0    anaconda
libffi                    3.2.1                h4deb6c0_3    anaconda
libgcc-ng                 9.1.0                hdf63c60_0    anaconda
libgfortran-ng            7.3.0                hdf63c60_0    anaconda
libglu                    9.0.0                hf484d3e_1    anaconda
liblief                   0.9.0                h7725739_2    anaconda
libpng                    1.6.37               hbc83047_0    anaconda
libstdcxx-ng              9.1.0                hdf63c60_0    anaconda
libtiff                   4.1.0                h2733197_0    anaconda
libuuid                   1.0.3                h1bed415_2    anaconda
libxcb                    1.13                 h1bed415_1    anaconda
libxml2                   2.9.9                hea5a465_1    anaconda
localization-survey       0.0                       dev_0    <develop>
lz4-c                     1.8.1.2              h14c3975_0    anaconda
lzo                       2.10                 h1bfc0ba_1    anaconda
mako                      1.1.0                    pypi_0    pypi
markupsafe                1.1.1            py36h7b6447c_0    anaconda
matplotlib                3.1.3                    py36_0    anaconda
matplotlib-base           3.1.3            py36hef1b27d_0    anaconda
mkl                       2019.5                      281    anaconda
mkl-service               2.3.0            py36he904b0f_0    anaconda
mkl_fft                   1.0.15           py36ha843d7b_0    anaconda
mkl_random                1.1.0            py36hd6b4f25_0    anaconda
more-itertools            8.2.0                      py_0    anaconda
mpld3                     0.3                      py36_0    anaconda
ncurses                   6.1                  he6710b0_1    anaconda
networkx                  2.4                        py_0    anaconda
numexpr                   2.7.1            py36h423224d_0    anaconda
numpy                     1.14.6           py36h3b04361_4    anaconda
numpy-base                1.14.6           py36h81de0dd_4    anaconda
nvidia-ml-py3             7.352.0                  pypi_0    pypi
olefile                   0.46                     py36_0    anaconda
openssl                   1.1.1                h7b6447c_0    anaconda
packaging                 20.1                       py_0    anaconda
pandas                    0.25.1           py36he6710b0_0    anaconda
pango                     1.42.4               h049681c_0    anaconda
patchelf                  0.10                 he6710b0_0    anaconda
pcre                      8.43                 he6710b0_0    anaconda
pillow                    7.0.0            py36hb39fc2d_0    anaconda
pip                       20.0.2                   py36_1    anaconda
pixman                    0.38.0               h7b6447c_0    anaconda
pkginfo                   1.5.0.1                  py36_0    anaconda
pluggy                    0.13.1                   py36_0    anaconda
portend                   2.5                        py_0    anaconda
psutil                    5.6.7            py36h7b6447c_0    anaconda
py                        1.8.1                      py_0    anaconda
py-lief                   0.9.0            py36h7725739_2    anaconda
pycairo                   1.19.0           py36h2a1e443_0    anaconda
pycosat                   0.6.3            py36h7b6447c_0    anaconda
pycparser                 2.19                     py36_0    anaconda
pycuda                    2019.1.2                 pypi_0    pypi
pyface                    6.1.2                    py36_0    anaconda
pyfftw                    v0.11.1          py36h39e3cac_0    david_baddeley
pygments                  2.5.2                      py_0    anaconda
pyme-depends              1.05             py36he2d8e94_0    david_baddeley
pyme-warp-drive           0.3                       dev_0    <develop>
pymecompress              0.1.4            py36he2d8e94_0    david_baddeley
pyopengl                  3.1.1a1                  py36_0    anaconda
pyopenssl                 19.1.0                   py36_0    anaconda
pyparsing                 2.4.6                      py_0    anaconda
pyqt                      5.9.2            py36h22d08a2_1    anaconda
pysocks                   1.7.1                    py36_0    anaconda
pytables                  3.4.2            py36h3b5282a_2    anaconda
pytest                    5.3.1                    py36_0    anaconda
python                    3.6.9                h265db76_0  
python-dateutil           2.8.1                      py_0    anaconda
python-libarchive-c       2.8                     py36_13    anaconda
python-microscopy         19.12.17         py36hba7baf9_0    <unknown>
pytools                   2019.1.1                 pypi_0    pypi
pytz                      2019.3                     py_0    anaconda
pywavelets                1.1.1            py36h7b6447c_0    anaconda
pyyaml                    5.3              py36h7b6447c_0    anaconda
qt                        5.9.7                h5867ecd_1    anaconda
readline                  7.0                  h7b6447c_5    anaconda
repoze.lru                0.7                      py36_0    anaconda
requests                  2.22.0                   py36_1    anaconda
routes                    2.4.1                    py36_0    anaconda
ruamel_yaml               0.15.87          py36h7b6447c_0    anaconda
scikit-image              0.15.0           py36he6710b0_0    anaconda
scikit-learn              0.22.1           py36hd81dba3_0    anaconda
scipy                     1.4.1            py36h0b6359f_0    anaconda
setuptools                45.2.0                   py36_0    anaconda
simplejson                3.17.0           py36h7b6447c_0    anaconda
sip                       4.19.13          py36he6710b0_0    anaconda
six                       1.14.0                   py36_0    anaconda
snowballstemmer           2.0.0                      py_0    anaconda
soupsieve                 1.9.5                    py36_0    anaconda
sphinx                    2.4.0                      py_0    anaconda
sphinxcontrib-applehelp   1.0.1                      py_0    anaconda
sphinxcontrib-devhelp     1.0.1                      py_0    anaconda
sphinxcontrib-htmlhelp    1.0.2                      py_0    anaconda
sphinxcontrib-jsmath      1.0.1                      py_0    anaconda
sphinxcontrib-qthelp      1.0.2                      py_0    anaconda
sphinxcontrib-serializinghtml 1.1.3                      py_0    anaconda
sqlite                    3.31.1               h7b6447c_0    anaconda
tempora                   1.14.1                     py_0    anaconda
tk                        8.6.8                hbc83047_0    anaconda
toolz                     0.10.0                     py_0    anaconda
toposort                  1.1                      py36_2    david_baddeley
tornado                   6.0.3            py36h7b6447c_3    anaconda
tqdm                      4.42.1                     py_0    anaconda
traits                    5.2.0            py36h7b6447c_0    anaconda
traitsui                  6.1.3                      py_0    anaconda
ujson                     1.35             py36h14c3975_0    anaconda
urllib3                   1.25.8                   py36_0    anaconda
wcwidth                   0.1.8                      py_0    anaconda
wheel                     0.34.2                   py36_0    anaconda
wxpython                  4.0.4            py36hc99224d_0    anaconda
xz                        5.2.4                h14c3975_4    anaconda
yaml                      0.1.7                h96e3832_1    anaconda
zc.lockfile               2.0                        py_0    anaconda
zeroconf                  0.23.0                   py36_3    david_baddeley
zipp                      2.2.0                      py_0    anaconda
zlib                      1.2.11               h7b6447c_3    anaconda
zstd                      1.3.7                h0b5b093_0    anaconda
(base) ubuntu@blofeld:~/code/pyme-conda-recipes$ conda build python-microscopy/
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Cloning into '/home/ubuntu/miniconda3/conda-bld/python-microscopy_1582040934172/work'...
done.
checkout: 'HEAD'
Your branch is up-to-date with 'origin/_conda_cache_origin_head'.
==> git log -n1 <==

commit 7354bd1b8677541dd1f2ac87f7e727054405ec69
Author: David Baddeley <david.baddeley.nz@gmail.com>
Date:   Mon Feb 17 12:58:00 2020 +1300

    ruleserver documentation updates

==> git describe --tags --dirty <==

20.02.12-87-g7354bd1

==> git status <==

On branch _conda_cache_origin_head
Your branch is up-to-date with 'origin/_conda_cache_origin_head'.

nothing to commit, working directory clean

Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from /home/ubuntu/code/pyme-conda-recipes/python-microscopy/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /home/ubuntu/code/pyme-conda-recipes/python-microscopy/conda_build_config.yaml
Attempting to finalize metadata for python-microscopy
INFO:conda_build.metadata:Attempting to finalize metadata for python-microscopy
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
BUILD START: ['python-microscopy-20.02.12-py36_0.tar.bz2']
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                                                                                                             

Leaving build/test directories:
  Work:
 /home/ubuntu/miniconda3/conda-bld/work 
  Test:
 /home/ubuntu/miniconda3/conda-bld/test_tmp 
Leaving build/test environments:
  Test:
source activate  /home/ubuntu/miniconda3/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p 
  Build:
source activate  /home/ubuntu/miniconda3/conda-bld/_build_env 


Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda_build/environ.py", line 753, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/plan.py", line 474, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
    should_retry_solve)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 158, in solve_for_diff
    force_remove, should_retry_solve)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 281, in solve_final_state
    ssc = self._run_sat(ssc)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 808, in _run_sat
    should_retry_solve=ssc.should_retry_solve
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 1318, in solve
    self.find_conflicts(specs, specs_to_add, history_specs)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 351, in find_conflicts
    raise UnsatisfiableError(bad_deps, strict=strict_channel_priority)
conda.exceptions.UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package numpy conflicts for:
pyme-depends -> numpy[version='1.11.*|1.14.*|1.9.*']
numpy[version='>=1.16.*']
pyme-depends -> matplotlib -> numpy[version='1.10.*|1.12.*|1.13.*|>=1.14.6,<2.0a0|1.8.*|1.7.*|1.6.*|1.5.*|>=1.13.3,<2.0a0|>=1.12.1,<2.0a0|>=1.11.3,<2.0a0|>=1.9.3,<2.0a0|>=1.9|>=1.12|>=1.15.1,<2.0a0']

Package python conflicts for:
python=3.6
numpy[version='>=1.16.*'] -> mkl_fft -> python[version='>=3.5,<3.6.0a0']
pyme-depends -> cherrypy -> python[version='2.6.*|3.3.*|3.4.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.5']
pyme-depends -> python[version='2.7.*|>=3.6,<3.7.0a0']
numpy[version='>=1.16.*'] -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0']

Package _libgcc_mutex conflicts for:
python=3.6 -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex=[build=main]
numpy[version='>=1.16.*'] -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex=[build=main]

Package setuptools conflicts for:
pyme-depends -> cherrypy -> setuptools
python=3.6 -> pip -> setuptoolsThe following specifications were found to be incompatible with your CUDA driver:

  - feature:/linux-64::__cuda==7.5=0

Your installed CUDA driver is: 7.5


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 456, in main
    execute(sys.argv[1:])
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 447, in execute
    verify=args.verify, variants=args.variants)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda_build/api.py", line 208, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 2314, in build_tree
    notest=notest,
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1397, in build
    create_build_envs(m, notest)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1281, in create_build_envs
    raise e
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1271, in create_build_envs
    channel_urls=tuple(m.config.channel_urls))
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda_build/environ.py", line 755, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {'feature:/linux-64::__cuda==7.5=0'}
(base) ubuntu@blofeld:~/code/pyme-conda-recipes$ 

```

**Comment by barentine** [comment]
Issue is only present with dependency conflicts and conda version 4.8. See [here](https://github.com/conda/conda/issues/9681). Shouldn't be an issue for people if they use the conda recipes as is
